-- local null_ls = require("null-ls")
-- -- local cspell = require("cspell")
--
-- local lint = null_ls.builtins.diagnostics
--
-- -- local cspell_config = {
-- --     config_file_preferred_name = "~/.cspell.json",
-- -- }
--
-- local sources = {
--     -- cspell.diagnostics,
--     -- cspell.code_actions
--     lint.cspell
-- }
--
-- null_ls.setup({
--     debug = true,
--     sources = sources
-- })
